import Script from "next/script"
import ThemeProvider from "../src/layout/provider"
import StoreProvider from "../(app)/StoreProvider"
import { Toaster } from "react-hot-toast"
import { SpeedInsights } from "@vercel/speed-insights/next"
import '@pathscale/fonts-sansation'
import "./globals.css";
import Header from "../src/layout/Header/Header"


export const metadata = {
  title: 'Directory Manager',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
       <Script
        src="https://www.googletagmanager.com/gtag/js?id=G-JTKN6WC9QS"
        strategy="afterInteractive"
      />
      <Script
        id="google-analytics"
        strategy="afterInteractive">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-JTKN6WC9QS');
        `}
      </Script>
      <link rel="icon" type="image/png" href="/images/defaulticon-light.png" />

      <ThemeProvider>
        <body>
          <StoreProvider>
            <Toaster toastOptions={{
                className: 'dark:bg-gray-800 bg-white dark:border-gray-600 border-gray-200 dark:text-white text-black',
                style: {
                  padding: '16px',
                },
              }}  position="top-right" 
            />
            <div className="flex 2xl:container">
              <div className="flex flex-col min-h-screen flex-grow overflow-x-hidden max-w-full">
                <Header />
                <SpeedInsights />
                <main>{children}</main>
              </div>
            </div>
          </StoreProvider>
        </body>
      </ThemeProvider>
    </html>
  )
}
